name: Assignment 1 - Email

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # REQUIRED: Step name with your email
      - name: 24f2000323@ds.study.iitm.ac.in
        run: echo "Hello, world!"
